# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10016d4190d15b07b8bc3520848e5f5897b04d834b00bbb4bba6be4f16d27c5141ec034112a8072293bf897a8e1c050aa2d1a878306f6742974cb53cb2fc604f

test:
  secret_key_base: b3ac42edaa1b3dd4ef4640dcc01a5334325ec410560c252e83fa0aebdd9ba03a0cc7bda39bcfef0253d06d6caa552c18df0d8a43d7827d8924a5a8f3e81254a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
